live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/nord.toml",
    "~/.config/alacritty/keybinds.toml"
]

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16
#normal.family = "Courier Prime"
#bold.family = "Courier Prime"
#italic.family = "Courier Prime"
#bold_italic.family = "Courier Prime"
#normal.family = "MartianMono Nerd Font"
#bold.family = "MartianMono Nerd Font"
#italic.family = "MartianMono Nerd Font"
#bold_italic.family = "MartianMono Nerd Font"
normal.family = "Fira Code"
bold.family = "Fira Code"
italic.family = "Fira Code"
bold_italic.family = "Fira Code"



[selection]
save_to_clipboard = true

[window]
opacity = 1.0
option_as_alt = "Both"
padding.x = 0
padding.y = 0

[bell]
command = { program = "osascript", args = ["-e", "beep"] }
